language: node_js
dist: bionic

before_script: |
  yarn build
  node packages/pg/script/create-test-tables.js postgresql:///

env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres

node_js:
  - 14

addons:
  postgresql: '10'

matrix:
  include:
    - node_js: lts/erbium
      addons:
        postgresql: '9.4'

    # PostgreSQL 9.2 only works on precise
    - node_js: lts/carbon
      addons:
        postgresql: '9.2'
      dist: precise
